export const pastQuotes = [
  "You still burn stuff for fuel? Adorable.",
  "This is before the oceans turned silver.",
  "I forgot how much the past smells.",
  "No neural mesh, no ambient AI... how do you even think?",
  "Ah, the age of wires and walls.",
  "Your sky still has stars. That's rare.",
  "I miss the taste of the future's modified fruit.",
  "This was before the Second Moon, right?",
  "You still use hands to build things?",
  "I read about this era in quantum school - never thought I'd smell it.",
  "Before the Merge, before the Silence... it's all so noisy.",
  "Your wars are so analog.",
  "This is the century where people still feared machines. Imagine that!",
  "I'm standing in a museum piece. It's quite amazing to see things were like up close.",
  "You still sleep eight hours? That's inefficient.",
  "This was before the Great Upload. Fascinating, everything is so... simple.",
  "I forgot how slow time feels here.",
  "Carbon-based life still dominates. How quaint.",
  "This is the age of paper and pride.",
  "I came from a time where memories are traded like currency.",
];

export const futureQuotes = [
  "I thought my century was advanced — this is alien.",
  "The stars speak now. We just had to learn to listen.",
  "I blinked, and humanity became something else.",
  "They don't use names anymore. Just frequencies.",
  "Time isn't linear here. It folds like origami.",
  "Earth? That's a myth they teach in dreamschool.",
  "I saw a sunrise on a planet that doesn't rotate.",
  "They've cured death — but forgot how to live. Ironic.",
  "People communicate through shared memories now, it's an unusual feeling.",
  "Gravity is optional in most cities.",
  "I met a civilization that never needed language. Quite fascinating really.",
  "They archive emotions like books.",
  "The oceans are sentient. And they're poets.",
  "I walked through a museum of extinct thoughts.",
  "They don't build with matter anymore — just intention.",
  "I saw the last tree. It was glowing.",
  "They replaced politics with consensus algorithms.",
  "I tasted music. It was bitter and beautiful.",
  "The future isn't chrome — it's quiet.",
  "We became light. And then we moved on.",
];
